package com.rieno.gadgetsandgizmos.tools;

import com.rieno.gadgetsandgizmos.compat.computercraft.api.ComputerCraftPeripheralManifest;
import com.rieno.gadgetsandgizmos.compat.computercraft.api.PeripheralDocumentation;
import com.rieno.gadgetsandgizmos.compat.computercraft.api.PeripheralTypeDoc;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;

// Generate the checked-in CC ROM catalogue from peripheral annotations

public final class GenerateComputerCraftDocs {
    private GenerateComputerCraftDocs() {
    }
    public static void main(String[] args) throws Exception {
        boolean check = args.length == 2 && "--check".equals(args[0]);
        if ((!check && args.length != 1) || (check && args.length != 2)) {
            throw new IllegalArgumentException(
                    "usage: GenerateComputerCraftDocs [--check] <output-file>");
        }
        Path output = Path.of(args[args.length - 1]);
        Map<String, Map<String, PeripheralDocumentation.Entry>> types =
                new TreeMap<>();
        ClassLoader loader = GenerateComputerCraftDocs.class.getClassLoader();

        for (String className : ComputerCraftPeripheralManifest.CLASSES) {
            Class<?> peripheral = Class.forName(className, false, loader);
            PeripheralTypeDoc typeDoc = peripheral.getAnnotation(PeripheralTypeDoc.class);
            if (typeDoc == null
                    || typeDoc.value().length + typeDoc.prefixes().length == 0) {
                throw new IllegalStateException(className
                        + " has no @PeripheralTypeDoc type or prefix");
            }
            List<String> typeKeys = new ArrayList<>();
            for (String value : typeDoc.value()) {
                typeKeys.add(required(value, className));
            }
            for (String prefix : typeDoc.prefixes()) {
                typeKeys.add(required(prefix, className) + "*");
            }
            PeripheralDocumentation.Catalog catalog =
                    PeripheralDocumentation.catalog(peripheral);
            for (String typeKey : typeKeys) {
                Map<String, PeripheralDocumentation.Entry> methods =
                        types.computeIfAbsent(typeKey, ignored -> new TreeMap<>());
                for (PeripheralDocumentation.Entry entry : catalog.entries()) {
                    PeripheralDocumentation.Entry previous = methods.putIfAbsent(
                            entry.name(), entry);
                    if (previous != null && !previous.equals(entry)) {
                        throw new IllegalStateException("Conflicting " + typeKey
                                + "." + entry.name() + " documentation");
                    }
                }
            }
        }

        String generated = emit(types);
        if (check) {
            if (!Files.exists(output)
                    || !Files.readString(output, StandardCharsets.UTF_8)
                    .equals(generated)) {
                throw new IllegalStateException(output
                        + " is stale; run generateComputerCraftDocs");
            }
            return;
        }
        Files.createDirectories(output.getParent());
        Files.writeString(output, generated, StandardCharsets.UTF_8);
    }

    private static String required(String value, String owner) {
        String normalized = value == null ? "" : value.strip();
        if (normalized.isBlank()) {
            throw new IllegalStateException(owner
                    + " declares a blank peripheral type");
        }
        return normalized;
    }

    private static String emit(
            Map<String, Map<String, PeripheralDocumentation.Entry>> types
    ) {
        StringBuilder out = new StringBuilder(
                "-- Generated by generateComputerCraftDocs; do not edit.\nreturn {\n");
        types.forEach((type, methods) -> {
            out.append("  [").append(lua(type)).append("] = {\n");
            methods.forEach((name, entry) -> {
                out.append("    [").append(lua(name)).append("] = {\n")
                        .append("      signature = ").append(lua(entry.signature()))
                        .append(",\n      description = ")
                        .append(lua(entry.description()))
                        .append(",\n      since = ").append(lua(entry.since()))
                        .append(",\n      deprecatedBy = ")
                        .append(lua(entry.deprecatedBy()))
                        .append(",\n      examples = {");
                for (String example : entry.examples()) {
                    out.append(lua(example)).append(',');
                }
                out.append("},\n    },\n");
            });
            out.append("  },\n");
        });
        return out.append("}\n").toString();
    }

    private static String lua(String value) {
        StringBuilder out = new StringBuilder("\"");
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\' -> out.append("\\\\");
                case '"' -> out.append("\\\"");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (character < 32) {
                        out.append(String.format(Locale.ROOT,
                                "\\%03d", (int) character));
                    } else {
                        out.append(character);
                    }
                }
            }
        }
        return out.append('"').toString();
    }
}
