modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mixins]]
config="createthrusters-main.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aeronautics"
type="required"
versionRange="[1.2.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="flywheel"
type="required"
versionRange="[${flywheel_version},2.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="sable"
type="required"
versionRange="[${sable_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="${library_mod_id}"
type="required"
versionRange="[${mod_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="simulated"
type="required"
versionRange="[1.2.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="computercraft"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="computed"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="synaxis"
type="optional"
versionRange="[1.5.0,1.6.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="simulatedcoasters"
type="optional"
versionRange="[0.1.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create_connected"
type="optional"
versionRange="[1.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sqlite_jdbc"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="emi"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="roughlyenoughitems"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[15.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="[9.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aeroclaims"
type="optional"
versionRange="[0.9.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aeroworks"
type="optional"
versionRange="[1.2.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="strawstatues"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
